/* List based upon the items created for use in an active Calendar App on a person's device -- from 01.json */

/*
    char * calendar_id;
    char * calendar_title;
    char * calendar_year;
    char * calendar_month;
    char * calendar_day;
    char * calendar_time_start;
    char * calendar_time_end;
    char * calendar_time_duration;
    char * calendar_time_period;
    char * calendar_time_zone;
    char * calendar_description;
    char * calendar_repeat;
    char * calendar_alert;
    char * calendar_show_as;
    char * calendar_notes;
    const lv_img_dsc_t * calendar_event_icon;
    const lv_img_dsc_t * calendar_type_icon;
*/

/* Create and initialize the Calendar_00 list */
static calendar_item calendar_00_list[] = {
    {
        .calendar_id = "0008",
        .calendar_year = "2024",
		.calendar_month = "September",
        .calendar_day = "09",
        .calendar_title = "Stuart",
        .calendar_time_start = "08:00",
        .calendar_time_end = "09:00",
        .calendar_time_zone = "PST",
        .calendar_time_duration = "1",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "Hayy Caramba, Banaaaaaa",
        .calendar_type_icon = &Icon_Empty_Dude,
        .calendar_notes = "cal_01"
    },
    {
        .calendar_id = "0009",
        .calendar_year = "2024",
		.calendar_month = "September",
        .calendar_day = "09",
        .calendar_title = "Kevin meeting",
        .calendar_time_start = "10:00",
        .calendar_time_end = "12:00",
        .calendar_time_zone = "PST",
        .calendar_time_duration = "2",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "Luca Banonooo, no no. C'est la Bananaaaaaa",
        .calendar_type_icon = &Icon_Phone,
        .calendar_notes = "cal_01"
    },
    {
        .calendar_id = "0010",
        .calendar_year = "2024",
		.calendar_month = "September",
        .calendar_day = "09",
        .calendar_title = "Mini Boss",
        .calendar_time_start = "12:00",
        .calendar_time_end = "13:00",
        .calendar_time_zone = "PST",
        .calendar_time_duration = "1",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "Macalo yeahhhhh, planning party",
        .calendar_type_icon = &Icon_Birthday,
        .calendar_notes = "cal_01"
    },
    {
        .calendar_id = "0011",
        .calendar_year = "2024",
		.calendar_month = "September",
        .calendar_day = "09",
        .calendar_title = "Stuart, Kevin & Bob",
        .calendar_time_start = "15:00",
        .calendar_time_end = "16:00",
        .calendar_time_zone = "PST",
        .calendar_time_duration = "1",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "Balatopa, okkk. Pancakeeeee",
        .calendar_type_icon = &Icon_Empty_Dude,
        .calendar_notes = "cal_01"
    },
    {

        .calendar_id = "0015",
        .calendar_year = "2024",
		.calendar_month = "September",
        .calendar_day = "13",
        .calendar_title = "Talk with Dark Vader",
        .calendar_time_start = "08:00",
        .calendar_time_end = "10:00",
        .calendar_time_zone = "PST",
        .calendar_time_duration = "2",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "Finishing the Death Star",
        .calendar_type_icon = &Icon_Phone,
        .calendar_notes = "cal_02"
    },
    {
        .calendar_id = "0016",
        .calendar_year = "2024",
		.calendar_month = "September",
        .calendar_day = "13",
        .calendar_title = "Talk with Obi-Wan Kenobi",
        .calendar_time_start = "10:00",
        .calendar_time_end = "12:00",
        .calendar_time_zone = "PST",
        .calendar_time_duration = "2",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "Planning to party with the Force and Dark side people",
        .calendar_type_icon = &Icon_Phone,
        .calendar_notes = "cal_02"
    },
    {
        .calendar_id = "0017",
        .calendar_year = "2024",
		.calendar_month = "September",
        .calendar_day = "13",
        .calendar_title = "Dr. Emilio Lizardo joining",
        .calendar_time_start = "12:00",
        .calendar_time_end = "14:00",
        .calendar_time_zone = "PST",
        .calendar_time_duration = "2",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "Talk about the party organized by the dark force",
        .calendar_type_icon = &Icon_Empty_Dude,
        .calendar_notes = "cal_02"
    },
    {
        .calendar_id = "0018",
        .calendar_year = "2024",
		.calendar_month = "September",
        .calendar_day = "16",
        .calendar_title = "Lone Starr joining",
        .calendar_time_start = "16:00",
        .calendar_time_end = "18:00",
        .calendar_time_zone = "PST",
        .calendar_time_duration = "2",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "Talk about the party organized by the dark force",
        .calendar_type_icon = &Icon_Empty_Dude,
        .calendar_notes = "cal_03"
    },
    {
        .calendar_id = "0019",
        .calendar_year = "2024",
		.calendar_month = "September",
        .calendar_day = "16",
        .calendar_title = "Topper Harley Birthday",
        .calendar_time_start = "09:00",
        .calendar_time_end = "10:00",
        .calendar_time_zone = "PST",
        .calendar_time_duration = "1",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "Are too too too too too too too too too too too...",
        .calendar_type_icon = &Icon_Birthday,
        .calendar_notes = "cal_03"
    },
    {
        .calendar_id = "0020",
        .calendar_year = "2024",
		.calendar_month = "September",
        .calendar_day = "16",
        .calendar_title = "Jim 'Wash Out' Pfaffenbach Birthday",
        .calendar_time_start = "10:00",
        .calendar_time_end = "11:00",
        .calendar_time_zone = "PST",
        .calendar_time_duration = "1",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "They put me in charge of radar! From now on, I'll be your eyes on the ground!",
        .calendar_type_icon = &Icon_Birthday,
        .calendar_notes = "cal_03"
    },
    {
        .calendar_id = "0021",
        .calendar_year = "2024",
		.calendar_month = "September",
        .calendar_day = "20",
        .calendar_title = "Banzai back to Earth ",
        .calendar_time_start = "13:00",
        .calendar_time_end = "14:00",
        .calendar_time_zone = "EST",
        .calendar_time_duration = "1",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "4 Pennsylvania Plaza, New York, NJ 08004",
        .calendar_show_as = "busy",
        .calendar_description = "Destroy Whorfin and the other Red Lectroids",
        .calendar_type_icon = &Icon_Empty_Dude,
        .calendar_notes = "cal_04"
    },
    {
        .calendar_id = "0022",
        .calendar_year = "2024",
		.calendar_month = "September",
        .calendar_day = "20",
        .calendar_title = "Dark Helmet",
        .calendar_time_start = "10:00",
        .calendar_time_end = "11:00",
        .calendar_time_zone = "EST",
        .calendar_time_duration = "1",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "Rescue Princess Vespa and save Planet Druidia",
        .calendar_type_icon = &Icon_Phone,
        .calendar_notes = "cal_04"
    },
    {
        .calendar_id = "0023",
        .calendar_year = "2024",
		.calendar_month = "September",
        .calendar_day = "20",
        .calendar_title = "President Skroob",
        .calendar_time_start = "11:00",
        .calendar_time_end = "12:00",
        .calendar_time_zone = "EST",
        .calendar_time_duration = "1",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "Negotiate fresh air from Planet Druidia",
        .calendar_type_icon = &Icon_Empty_Dude,
        .calendar_notes = "cal_04"
    },
    {
        .calendar_id = "0024",
        .calendar_year = "2024",
		.calendar_month = "September",
        .calendar_day = "23",
        .calendar_title = "Louis XIV",
        .calendar_time_start = "10:00",
        .calendar_time_end = "11:00",
        .calendar_time_zone = "EST",
        .calendar_time_duration = "1",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "It's good to be the king",
        .calendar_type_icon = &Icon_Birthday,
        .calendar_notes = "cal_05"
    },
    {
        .calendar_id = "0025",
        .calendar_year = "2024",
		.calendar_month = "September",
        .calendar_day = "23",
        .calendar_title = "Napoleon Bonaparte",
        .calendar_time_start = "11:00",
        .calendar_time_end = "12:00",
        .calendar_time_zone = "EST",
        .calendar_time_duration = "1",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "In politics, stupidity is not a handicap",
        .calendar_type_icon = &Icon_Birthday,
        .calendar_notes = "cal_05"
    },
    {
        .calendar_id = "0026",
        .calendar_year = "2024",
		.calendar_month = "September",
        .calendar_day = "24",
        .calendar_title = "Buckaroo Banzai",
        .calendar_time_start = "10:00",
        .calendar_time_end = "12:00",
        .calendar_time_zone = "EST",
        .calendar_time_duration = "2",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "Across the 8th Dimension experiment",
        .calendar_type_icon = &Icon_Phone,
        .calendar_notes = "cal_06"
    },
    {
        .calendar_id = "0027",
        .calendar_year = "2024",
		.calendar_month = "September",
        .calendar_day = "24",
        .calendar_title = "crime-fighting team",
        .calendar_time_start = "14:00",
        .calendar_time_end = "15:00",
        .calendar_time_zone = "EST",
        .calendar_time_duration = "1",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "Meet the Hong Kong Cavaliers",
        .calendar_type_icon = &Icon_Empty_Dude,
        .calendar_notes = "cal_06"
    },
    {
        .calendar_id = "0028",
        .calendar_year = "2024",
		.calendar_month = "September",
        .calendar_day = "26",
        .calendar_title = "Capitaine Ed Hocken meeting",
        .calendar_time_start = "10:00",
        .calendar_time_end = "11:00",
        .calendar_time_zone = "EST",
        .calendar_time_duration = "1",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "Who is the auditor?",
        .calendar_type_icon = &Icon_Empty_Dude,
        .calendar_notes = "cal_07"
    },
    {
        .calendar_id = "0029",
        .calendar_year = "2024",
		.calendar_month = "September",
        .calendar_day = "26",
        .calendar_title = "Frank Drebbin Birthday",
        .calendar_time_start = "14:00",
        .calendar_time_end = "15:00",
        .calendar_time_zone = "EST",
        .calendar_time_duration = "1",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "Okay, than after he shot the teller, who shot him twice?",
        .calendar_type_icon = &Icon_Birthday,
        .calendar_notes = "cal_07"
    },
    {
        .calendar_id = "0030",
        .calendar_year = "2024",
		.calendar_month = "September",
        .calendar_day = "30",
        .calendar_title = "Meeting Mr. Unger & Mr. Dunn",
        .calendar_time_start = "10:00",
        .calendar_time_end = "11:00",
        .calendar_time_zone = "EST",
        .calendar_time_duration = "1",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "Presentation navigator, Mr. Unger, and your first officer Mr. Dunn",
        .calendar_type_icon = &Icon_Empty_Dude,
        .calendar_notes = "cal_08"
    },
    {
        .calendar_id = "end",
        .calendar_notes = "TAP HERE\nTo import\nyour Contacts",
    },
};