/* List based upon the items created for use in an active Calendar App on a person's device -- from 01.json */

/*
    char * calendar_id;
    char * calendar_title;
    char * calendar_year;
    char * calendar_month;
    char * calendar_day;
    char * calendar_time_start;
    char * calendar_time_end;
    char * calendar_time_duration;
    char * calendar_time_period;
    char * calendar_time_zone;
    char * calendar_description;
    char * calendar_repeat;
    char * calendar_alert;
    char * calendar_show_as;
    char * calendar_notes;
    const lv_img_dsc_t * calendar_event_icon;
    const lv_img_dsc_t * calendar_type_icon;
*/


/* Create and initialize the Calendar_00 list */
static calendar_item calendar_00_list[] = {
    {
        .calendar_id = "0001",
        .calendar_title = "Stuart",
        .calendar_year = "2024",
        .calendar_month = "July",
        .calendar_day = "9",
        .calendar_time_start = "08:00",
        .calendar_time_end = "09:00",
        .calendar_time_zone = "PST",
        .calendar_time_duration = "1",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "Hayy Caramba, Banaaaaaa",
        .calendar_type_icon = &Icon_Empty_Dude,
        .calendar_notes = ""
    },
    {
        .calendar_id = "0002",
        .calendar_year = "2024",
        .calendar_month = "July",
        .calendar_day = "9",
        .calendar_title = "Kevin meeting",
        .calendar_time_start = "10:00",
        .calendar_time_end = "12:00",
        .calendar_time_zone = "PST",
        .calendar_time_duration = "2",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "Luca Banonooo, no no. C'est la Bananaaaaaa",
        .calendar_type_icon = &Icon_Phone,
        .calendar_notes = ""
    },
    {
        .calendar_id = "0003",
        .calendar_year = "2024",
        .calendar_month = "July",
        .calendar_day = "9",
        .calendar_title = "Mini Boss",
        .calendar_time_start = "12:00",
        .calendar_time_end = "13:00",
        .calendar_time_zone = "PST",
        .calendar_time_duration = "1",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "Macalo yeahhhhh, planning party",
        .calendar_type_icon = &Icon_Birthday,
        .calendar_notes = ""
    },
    {
        .calendar_id = "0004",
        .calendar_year = "2024",
        .calendar_month = "July",
        .calendar_day = "9",
        .calendar_title = "Stuart, Kevin & Bob",
        .calendar_time_start = "15:00",
        .calendar_time_end = "16:00",
        .calendar_time_zone = "PST",
        .calendar_time_duration = "1",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "Balatopa, okkk. Pancakeeeee",
        .calendar_type_icon = &Icon_Empty_Dude,
        .calendar_notes = ""
    },
    {
        .calendar_id = "0005",
        .calendar_year = "2024",
        .calendar_month = "July",
        .calendar_day = "9",
        .calendar_title = "Meeting Gru",
        .calendar_time_start = "16:00",
        .calendar_time_end = "19:00",
        .calendar_time_zone = "PST",
        .calendar_time_duration = "3",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "Plan to steal the moon",
        .calendar_type_icon = &Icon_Phone,
        .calendar_notes = ""
    },
    {
        .calendar_id = "0006",
        .calendar_year = "2024",
        .calendar_month = "July",
        .calendar_day = "16",
        .calendar_title = "Talk with Dark Vader",
        .calendar_time_start = "08:00",
        .calendar_time_end = "10:00",
        .calendar_time_zone = "PST",
        .calendar_time_duration = "2",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "Finishing the Death Star",
        .calendar_type_icon = &Icon_Phone,
        .calendar_notes = ""
    },
    {
        .calendar_id = "0007",
        .calendar_year = "2024",
        .calendar_month = "July",
        .calendar_day = "16",
        .calendar_title = "Talk with Obi-Wan Kenobi",
        .calendar_time_start = "10:00",
        .calendar_time_end = "12:00",
        .calendar_time_zone = "PST",
        .calendar_time_duration = "2",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "Planning to party with the Force and Dark side people",
        .calendar_type_icon = &Icon_Phone,
        .calendar_notes = ""
    },
    {
        .calendar_id = "0008",
        .calendar_year = "2024",
        .calendar_month = "July",
        .calendar_day = "16",
        .calendar_title = "Dr. Emilio Lizardo joining",
        .calendar_time_start = "12:00",
        .calendar_time_end = "14:00",
        .calendar_time_zone = "PST",
        .calendar_time_duration = "2",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "Talk about the party organized by the dark force",
        .calendar_type_icon = &Icon_Empty_Dude,
        .calendar_notes = ""
    },
    {
        .calendar_id = "0009",
        .calendar_year = "2024",
        .calendar_month = "July",
        .calendar_day = "16",
        .calendar_title = "Lone Starr joining",
        .calendar_time_start = "16:00",
        .calendar_time_end = "18:00",
        .calendar_time_zone = "PST",
        .calendar_time_duration = "2",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "Talk about the party organized by the dark force",
        .calendar_type_icon = &Icon_Empty_Dude,
        .calendar_notes = ""
    },
    {   
        .calendar_id = "0010",
        .calendar_year = "2024",
        .calendar_month = "August",
        .calendar_day = "1",
        .calendar_title = "Invade planet Earth",
        .calendar_time_start = "08:00",
        .calendar_time_end = "10:00",
        .calendar_time_zone = "EST",
        .calendar_time_duration = "2",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "4 Pennsylvania Plaza, New York, NJ 08004",
        .calendar_show_as = "busy",
        .calendar_description = "Constructed an escape vessel so the Red Lectroids could return to Planet 10",
        .calendar_type_icon = &Icon_Phone,
        .calendar_notes = ""
    },
    {
        .calendar_id = "0011",
        .calendar_year = "2024",
        .calendar_month = "August",
        .calendar_day = "1",
        .calendar_title = "Banzai back to Earth ",
        .calendar_time_start = "10:00",
        .calendar_time_end = "11:00",
        .calendar_time_zone = "EST",
        .calendar_time_duration = "1",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "4 Pennsylvania Plaza, New York, NJ 08004",
        .calendar_show_as = "busy",
        .calendar_description = "Destroy Whorfin and the other Red Lectroids",
        .calendar_type_icon = &Icon_Empty_Dude,
        .calendar_notes = ""
    },
    {
        .calendar_id = "0012",
        .calendar_year = "2024",
        .calendar_month = "August",
        .calendar_day = "1",
        .calendar_title = "Dr. Frederick Frankenstein",
        .calendar_time_start = "11:00",
        .calendar_time_end = "12:00",
        .calendar_time_zone = "EST",
        .calendar_time_duration = "1",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "Help Igor with that hump.",
        .calendar_type_icon = &Icon_Phone,
        .calendar_notes = ""
    },
    {
        .calendar_id = "0013",
        .calendar_year = "2024",
        .calendar_month = "August",
        .calendar_day = "1",
        .calendar_title = "Igor",
        .calendar_time_start = "14:00",
        .calendar_time_end = "15:00",
        .calendar_time_zone = "EST",
        .calendar_time_duration = "1",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "4 Pennsylvania Plaza, New York, NJ 08004",
        .calendar_show_as = "busy",
        .calendar_description = "Well, why isn't it Froaderick Fronkensteen?",
        .calendar_type_icon = &Icon_Empty_Dude,
        .calendar_notes = ""
    },
    {
        .calendar_id = "0014",
        .calendar_year = "2024",
        .calendar_month = "August",
        .calendar_day = "15",
        .calendar_title = "Louis XIV",
        .calendar_time_start = "10:00",
        .calendar_time_end = "11:00",
        .calendar_time_zone = "EST",
        .calendar_time_duration = "1",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "It's good to be the king",
        .calendar_type_icon = &Icon_Birthday,
        .calendar_notes = ""
    },
    {
        .calendar_id = "0015",
        .calendar_year = "2024",
        .calendar_month = "August",
        .calendar_day = "15",
        .calendar_title = "Napoléon Bonaparte",
        .calendar_time_start = "11:00",
        .calendar_time_end = "12:00",
        .calendar_time_zone = "EST",
        .calendar_time_duration = "1",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "In politics, stupidity is not a handicap",
        .calendar_type_icon = &Icon_Birthday,
        .calendar_notes = ""
    },
    {
        .calendar_id = "0016",
        .calendar_year = "2024",
        .calendar_month = "August",
        .calendar_day = "15",
        .calendar_title = "Buckaroo Banzai",
        .calendar_time_start = "14:00",
        .calendar_time_end = "16:00",
        .calendar_time_zone = "EST",
        .calendar_time_duration = "2",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "Across the 8th Dimension experiment",
        .calendar_type_icon = &Icon_Phone,
        .calendar_notes = ""
    },
    {
        .calendar_id = "0017",
        .calendar_year = "2024",
        .calendar_month = "August",
        .calendar_day = "15",
        .calendar_title = "Jim 'Wash Out' Pfaffenbach Job",
        .calendar_time_start = "10:00",
        .calendar_time_end = "11:00",
        .calendar_time_zone = "PST",
        .calendar_time_duration = "1",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "They put me in charge of radar! From now on, I'll be your eyes on the ground!",
        .calendar_type_icon = &Icon_Birthday,
        .calendar_notes = ""
    },
    {
        .calendar_id = "0018",
        .calendar_year = "2024",
        .calendar_month = "September",
        .calendar_day = "10",
        .calendar_title = "Capitaine Ed Hocken meeting",
        .calendar_time_start = "10:00",
        .calendar_time_end = "11:00",
        .calendar_time_zone = "EST",
        .calendar_time_duration = "1",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "Who is the auditor?",
        .calendar_type_icon = &Icon_Empty_Dude,
        .calendar_notes = ""
    },
    {
        .calendar_id = "0019",
        .calendar_year = "2024",
        .calendar_month = "September",
        .calendar_day = "10",
        .calendar_title = "Frank Drebbin Birthday",
        .calendar_time_start = "11:00",
        .calendar_time_end = "12:00",
        .calendar_time_zone = "EST",
        .calendar_time_duration = "1",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "Okay, than after he shot the teller, who shot him twice?",
        .calendar_type_icon = &Icon_Birthday,
        .calendar_notes = ""
    },
    {
        .calendar_id = "0020",
        .calendar_year = "2024",
        .calendar_month = "September",
        .calendar_day = "10",
        .calendar_title = "Meeting Mr. Unger & Mr. Dunn",
        .calendar_time_start = "13:00",
        .calendar_time_end = "14:00",
        .calendar_time_zone = "EST",
        .calendar_time_duration = "1",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "Presentation navigator, Mr. Unger, and your first officer Mr. Dunn",
        .calendar_type_icon = &Icon_Empty_Dude,
        .calendar_notes = ""
    },
    {
        .calendar_id = "0021",
        .calendar_year = "2024",
        .calendar_month = "September",
        .calendar_day = "10",
        .calendar_title = "Sell my plan",
        .calendar_time_start = "15:00",
        .calendar_time_end = "16:00",
        .calendar_time_zone = "PST",
        .calendar_time_duration = "1",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "4160 Country Club, Long Beach, CA 90807",
        .calendar_show_as = "busy",
        .calendar_description = "Convince Cameron to come pick me up",
        .calendar_type_icon = &Icon_Phone,
        .calendar_notes = ""
   },
   {
        .calendar_id = "0022",
        .calendar_year = "2024",
        .calendar_month = "September",
        .calendar_day = "20",
        .calendar_title = "Discussion with Bart & Jim",
        .calendar_time_start = "09:00",
        .calendar_time_end = "10:00",
        .calendar_time_zone = "EST",
        .calendar_time_duration = "1",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "Why, Rhett! How many times have I told you to wash up after weekly cross burning?",
        .calendar_type_icon = &Icon_Phone,
        .calendar_notes = ""
    },
    {
        .calendar_id = "0023",
        .calendar_year = "2024",
        .calendar_month = "September",
        .calendar_day = "20",
        .calendar_title = "Caslte taken by who?",
        .calendar_time_start = "10:00",
        .calendar_time_end = "11:00",
        .calendar_time_zone = "EST",
        .calendar_time_duration = "1",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "Blinkin, listen to me. They've taken the castle!",
        .calendar_type_icon = &Icon_Empty_Dude,
        .calendar_notes = ""
    },
    {
        .calendar_id = "0024",
        .calendar_year = "2024",
        .calendar_month = "September",
        .calendar_day = "20",
        .calendar_title = "Meeting Malory Archer",
        .calendar_time_start = "11:00",
        .calendar_time_end = "12:00",
        .calendar_time_zone = "EST",
        .calendar_time_duration = "1",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "The classic Irishman’s dilemma: Do I eat the potato or do I let it ferment so I can drink it later?",
        .calendar_type_icon = &Icon_Phone,
        .calendar_notes = ""
    },
    {
        .calendar_id = "0025",
        .calendar_year = "2024",
        .calendar_month = "September",
        .calendar_day = "20",
        .calendar_title = "Birthday Doctor Krieger",
        .calendar_time_start = "14:00",
        .calendar_time_end = "15:00",
        .calendar_time_zone = "EST",
        .calendar_time_duration = "1",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "Yep Yep Yep",
        .calendar_type_icon = &Icon_Birthday,
        .calendar_notes = ""
    },
    {
        .calendar_id = "0026",
        .calendar_year = "2024",
        .calendar_month = "September",
        .calendar_day = "20",
        .calendar_title = "Chat with Pam Poovey",
        .calendar_time_start = "15:00",
        .calendar_time_end = "16:00",
        .calendar_time_zone = "EST",
        .calendar_time_duration = "1",
        .calendar_time_period = "hour",
        .calendar_repeat = "no",
        .calendar_alert = "1 day",
        .calendar_location = "",
        .calendar_show_as = "busy",
        .calendar_description = "Why on Earth do you feel you're qualified to be an ISIS field agent",
        .calendar_type_icon = &Icon_Empty_Dude,
        .calendar_notes = ""
    },
    {
        .calendar_id = "end",
        .calendar_notes = "TAP HERE\nTo import\nyour Contacts",
    },
};